GET http://localhost:3000/product
Origin: https://phonegigs.com

###

GET http://localhost:3000/product/zw8Jb2dB96oczQIotu0B
Origin: https://phonegigs.com

###

POST http://localhost:3000/product
Content-Type: application/json
Origin: https://phonegigs.com

{
	"quantity":10,
	"image":"https://m.media-amazon.com/images/I/81vDZyJQ-4L._SY550_.jpg",
	"make":"Samsung",
	"name":"Galaxy S20 FE",
	"price":32999,
	"description":"Samsung Galaxy's most advanced zoom ever will help you capture amazing things from far away. Galaxy S20's Hybrid Optic Zoom allows you to zoom up to x3 on anything that catches your eye with absolutely no loss of image quality. On top of that, you can enjoy Galaxy S20's Super Resolution Zoom, which allows you to carry on zooming all the way to x30*. So when you're at a the back of the crowd at a music festival, you can zoom to the front of the stage in no time."}


###

PATCH http://localhost:3000/product/zw8Jb2dB96oczQIotu0B
Content-Type: application/json
Origin: https://phonegigs.com

{
	"quantity": 10,
	"make": "Samsung"
}

###

DELETE http://localhost:3000/product/zw8Jb2dB96oczQIotu0B

### Auth

POST http://localhost:3000/auth/register
Content-Type: application/json
Origin: https://phonegigs.com

{
	"username": "Alison Alexandra 8",
	"password": "test1234"
}