GET http://localhost:3000/product

###

GET http://localhost:3000/product/TX1rSsjamfejvS5X9GpS

###

POST http://localhost:3000/product
Content-Type: application/json

{
	"quantity":10,
	"image":"https://m.media-amazon.com/images/I/81vDZyJQ-4L._SY550_.jpg",
	"make":"Samsung",
	"name":"Galaxy S20 FE",
	"price":32999,
	"description":"Samsung Galaxy's most advanced zoom ever will help you capture amazing things from far away. Galaxy S20's Hybrid Optic Zoom allows you to zoom up to x3 on anything that catches your eye with absolutely no loss of image quality. On top of that, you can enjoy Galaxy S20's Super Resolution Zoom, which allows you to carry on zooming all the way to x30*. So when you're at a the back of the crowd at a music festival, you can zoom to the front of the stage in no time."}


###

PATCH http://localhost:3000/product/TX1rSsjamfejvS5X9GpS
Content-Type: application/json

{
	"quantity": 10,
	"make": "Samsung"
}

###

DELETE http://localhost:3000/product/TX1rSsjamfejvS5X9GpS